sudo: required

services:
  - docker

before_install:
  - docker build -t alabianca/rapi-api-test:latest .

script:
 - echo "Should be running tests here..."
#   - docker run alabianca/rapi-api-test:latest go test ./...

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_TOKEN"
  app: "$HEROKU_APP_NAME"